FROM mysql:8.0-debian

RUN apt update && apt upgrade -y

COPY --link --chmod=644 /mysql/my.cnf /etc/mysql/my.cnf

RUN adduser webuser
RUN adduser --group webgroup
RUN adduser webuser webgroup

ENV MYSQL_ROOT_PASSWORD=123
ENV MYSQL_DATABASE=processwire
ENV MYSQL_USER=processwire
ENV MYSQL_PASSWORD=123